language: android
android:
  components:
    - platform-tools
    - tools
    - extra-android-m2repository
    - build-tools-30.0.2
    - android-30
    
before_install:
 - yes | sdkmanager "platforms;android-30"
 - chmod +x gradlew

script:
  - ./gradlew assembleFreeDebug
